defaults:
  -
    scope:
      path: ''

    values:
      layout: default

  -
    scope:
      path: ''
      type: posts

    values:
      layout: post
      parent: blog

  -
    scope:
      path: projects

    values:
      layout: project
      parent: projects

permalink: pretty
