defaults:
  -
    scope:
      path: ''

    values:
      layout: default

  -
    scope:
      path: ''
      type: posts

    values:
      layout: post

  -
    scope:
      path: projects

    values:
      layout: narrow

permalink: pretty
